title: The Federal Writer's Project - Project
tagline: A Critical Look at the FWA and it's Effects
description: How has the FWA Effected American Culture in the Decades Since 
banner: https://tile.loc.gov/storage-services/service/pnp/ds/07200/07256r.jpg
#favicon: <favicon url>
#logo: <logo url>

# When using a custom domain these fields must be updated to match
# the Github account and repository name
#acct: <GitHub account/username>
#repo: <GitHub repository>

######################################################
# Defines options shown in the header navigation menu
######################################################
nav:
- label: Contact the Juncture team
  icon: fas fa-envelope
  action: contact-us
- label: View page source
  icon: fas fa-file-code
  action: view-markdown


# If a contact-us action is defined for the nav menu a contact form will be enabled
# The following information is used in the display and processing of the contact form.
contactForm:
  to:
  - JSTOR Labs <labs@ithaka.org>
  subject: Juncture
